# Apenas Splunk – OTel collector agent nos 3 serviços
services:
  gateway-service:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://splunk-otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
  orders-service:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://splunk-otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
  payment-service:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://splunk-otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf

  splunk-otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:latest
    container_name: obs-splunk-otel
    user: "0:0"
    command: ["--config=/etc/otel/collector/custom_config.yaml"]
    environment:
      SPLUNK_ACCESS_TOKEN:     "${SPLUNK_ACCESS_TOKEN}"
      SPLUNK_REALM:            "${SPLUNK_REALM:-us0}"
      SPLUNK_MEMORY_TOTAL_MIB: "512"
      ENVIRONMENT:             "${ENVIRONMENT:-lab}"
      HOSTNAME_LAB:            "${HOSTNAME_LAB:-obs-lab-host}"
      SPLUNK_HEC_URL:          "${SPLUNK_HEC_URL}"
      SPLUNK_HEC_TOKEN:        "${SPLUNK_HEC_TOKEN}"
      SPLUNK_HEC_INDEX:        "${SPLUNK_HEC_INDEX:-main}"
      DB_USER:                 "${DB_USER:-obslab}"
      DB_PASSWORD:             "${DB_PASSWORD:?defina DB_PASSWORD no .env}"
      DB_NAME:                 "${DB_NAME:-inventory}"
    volumes:
      - ./splunk-otel-collector/config.yml:/etc/otel/collector/custom_config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /etc:/hostfs/etc:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "13133:13133"
      - "55679:55679"
    restart: unless-stopped
    networks: [obs-net]